### ISSUE TITLE
types inconsistency  

### ISSUE THREAD

**Issue by kobvel** [graphcool-examples/angular-graphql#5] opened 2017-07-06 13:17 UTC
Just after the first start getting errors related to types.

```
ERROR in /Users/kobvel/Workspace/examples/quickstart-with-apollo/node_modules/apollo-client-rxjs/build/src/Rx
ObservableQuery.d.ts (7,22): Class 'RxObservableQuery<T>' incorrectly extends base class 'Observable<ApolloQueryResult<T>>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<ApolloQueryResult<T>, ApolloQueryResult<R>>) => Observable<ApolloQueryResu...' is not assignable to type '<R>(operator: Operator<ApolloQueryResult<T>, R>) => Observable<R>'.
      Types of parameters 'operator' and 'operator' are incompatible.
        Type 'Operator<ApolloQueryResult<T>, R>' is not assignable to type 'Operator<ApolloQueryResult<T>, ApolloQueryResult<{}>>'.
          Type 'R' is not assignable to type 'ApolloQueryResult<{}>'.
```

**Comment by nikolasburk** [comment] 2017-07-20 16:31
Hey @kobvel, I can't reproduce the issue right now. When I'm running the app by following the instructions from the README, everything works out fine and I'm not getting any errors! Could you give a bit more precise information about how the issue comes up?

**Comment by asif633** [comment] 2017-08-01 15:01
I also got the issue. The steps I followed
1. git cloned the `https://github.com/graphcool-examples/angular-graphql`.
2. Set up graphcool account.
3. Changed the project uri in the `client.ts` file and also inside `package.json` file. Used the simple endpoint.
4. Run the `npm install` inside the  `quickstart-with-apollo` project. No error was shown.
5. Run `ng serve` and got the same error.

**Comment by claytoncasey01** [comment] 2017-08-07 19:53
A quick fix to the problem for now would be to set typescript to "typescript": "2.3.4" in your package.json file, that seems to fix the issue. This isn't specific to this project.

**Comment by marktani** [comment] 2017-08-07 19:56
That's great @claytoncasey01, could you send a quick PR? 🙂

**Comment by marktani** [comment] 2017-08-07 20:41
Closing this for now, even though #6 is only a temporary solution.

**Closed by marktani** 2017-08-07 20:41 UTC
Labels: bug
